### ISSUE TITLE
Incident API leaves description empty

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#1]
POST https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident
{
  "partnerId":"commvault",
  "caller_id":"technical_commvault_dev",
  "description":"test me baby one more time",
  "assignment_group":"BETR-BACKUP",
  "short_description":"other testing",
  "service_offering":"",
  "category":"incident",
  "cmdb_ci":"hcseh02",
  "contact_type":"",
  "impact":"",
  "location":"",
  "subcategory":"",
  "u_causing_ci":"hcszf02",
  "channel":"monitoring"
}

Field "description" should populate Description with the given Text, but Field remains empty in ServiceNow, all other Field-Values are processed as expected.
Content, Length or Format of the given String doesn't seem to matter. (Plain-Text, Escaped Text, HTML, long String, short string, single word)
sending the same Text-Samples to /incident/addComment in Field "comment" are processed and shown in ServiceNow

**Comment by timschaeren** [comment]
I have finally identified the issue. It's a rogue business rule resetting the description. This also happened on the UI - I'm amazed nobody else caught this. Fix is in the works - I'll update here.

**Comment by vollraths** [comment]
I take cash, twint or liquid compensation ;-) glad you found it.

**Comment by timschaeren** [comment]
Should be fixed - please check if the issue still shows up for you. We'll try and get some beer to you ;)

**Comment by vollraths** [comment]
description works now, thanks. 
assignment_group always defaults to "Anderes Team test" even if I set a, hopefully valid, string like "BETR-BACKUP". new issue for that?

**Comment by timschaeren** [comment]
> description works now, thanks. assignment_group always defaults to "Anderes Team test" even if I set a, hopefully valid, string like "BETR-BACKUP". new issue for that?

yes, please!
