### ISSUE TITLE
Validating given encodedQuery 'base_u_host_name=vaonq0' caused the following errors: EncodedQuery contains forbidden operator: 'nq'.

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#10]
Sending Queries to Data API seems to misinterpret some character-combinations in values as comparison parameters when using encodedQueries.
GET https://myit-dev.post.ch/api/x_ssagd_gen_read/v1/data/cmdb_ci_server_inline?limit=5&relations=ci_to_user_group_dynamic_inline&encodedQuery=base_u_host_name%3Dvaonq0
Throws
Error: 400{"name":"BadRequestRestException","message":"Validating given encodedQuery 'base_u_host_name=vaonq0' caused the following errors: EncodedQuery contains forbidden operator: 'nq'.","status":400}

**Comment by timschaeren** [comment]
I relayed the issue to [arc46](https://docs.arc46.io/squid/) - the developer of 'squid', the API you're using here.

The current version of squid no longer throws an error for this request, as the check for "NQ" now only triggers for `'^NQ'`
So `'xxxnqxx'` works, so does `'xxxNQxxx'`. `'xxx^NQxxx'` still will not work.

Feel free to post further enquiries about squid directly in the Swiss Post Channel on [support.arc46](https://support.arc46.io/g/post_ag).
Using your @post.ch email when you register will give you access.
