### ISSUE TITLE
Business Rules cause Calls to fault

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#2]
API currently throws faults when trying to create or update incidents
Add Comment
{
"name": "MyItRestException",
"message": "The action failed due to a business rule. Message: [\"This Incident is not of Channel \\\"Monitoring\\\".\",\"This incident does not have a correlation_display set.\"]",
"status": 500
}
Create Incident
{
"name": "MyItRestException",
"message": "The action failed due to a business rule. Message: [\"correlation_display is mandatory.\",\"u_causing_ci is mandatory.\"]",
"status": 500
}

**Comment by timschaeren** [comment]
Hi @vollraths can you please provide me with the sys-id of the incident you're having this issue with?

**Comment by vollraths** [comment]
PATCH incident/addComment Request was done against sys_id 0112576f87f375503efcec230cbb3546
Request-Body was:
{
    "partnerId": "commvault",
    "incidentId": "0112576f87f375503efcec230cbb3546",
    "comment": "Test me Baby one more Time"
}
POST incident failed so don't have a ID for that, maybe the return-header extract below is helpful instead:

Server: | snow_adc
-- | --
Date: | Thu, 18 Jul 2024 11:36:58 GMT-42m 53s
Content-Type: | application/problem+json
Transfer-Encoding: | chunked
Connection: | keep-alive
Server-Timing: | sem_wait;dur=0, sesh_wait;dur=0
Content-Encoding: | gzip
X-Is-Logged-In: | true
X-Transaction-ID: | 9d70bed087a7
X-Content-Type-Options: | nosniff
Strict-Transport-Security: | max-age=63072000; includeSubDomains
Set-Cookie: | BIGipServerpool_postchagdev=33 B, session, HttpOnly/
Set-Cookie: | glide_user_activity=129 B, session, HttpOnly/
Set-Cookie: | glide_node_id_for_js=65 B, session/
Set-Cookie: | glide_session_store=33 B, session, HttpOnly/

**Comment by vollraths** [comment]
Another Variant Appeared this Weekend:
PATCH https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident/addComment
{
"partnerId": "commvault",
"incidentId": "de691cac876bce903efcec230cbb352c",
"comment": "ErrorCode: [19:1328]\nFailureReason: [1] nodes failed. Failed node list: vin01a\nRecommended ..."
}

Returned 500 with: {"name":"MyItRestException","message":"The action failed due to a business rule. Message: [\"This Incident does not have a fieldname set.\",\"This can not be reopened\"]","status":500}

What fieldname should be missing is unclear and ticket is in status "new" so reopen comment is ambiguous. 

<HttpClient_3><system><startTime class="java.util.Date">1721588525</startTime><endTime class="java.util.Date"></endTime><status class="java.lang.String">PENDING</status><timedOut class="java.lang.Boolean">false</timedOut></system><output class="java.lang.String">{"name":"MyItRestException","message":"The action failed due to a business rule. Message: [\"This Incident does not have a fieldname set.\",\"This can not be reopened\"]","status":500}</output><statusCode class="java.lang.Integer">500</statusCode><statusText class="java.lang.String">Internal Server Error</statusText><headers class="workflow.types.data.DataRow"><col class="java.lang.String" name="Server">snow_adc</col><col class="java.lang.String" name="Date">Sun, 21 Jul 2024 19:02:05 GMT</col><col class="java.lang.String" name="Content-Type">application/problem+json</col><col class="java.lang.String" name="Transfer-Encoding">chunked</col><col class="java.lang.String" name="Connection">keep-alive</col><col class="java.lang.String" name="Set-Cookie">glide_session_store=0023FF1587A782146DC863540CBB35A7; Max-Age=1800; Expires=Sun, 21-Jul-2024 19:32:05 GMT; Path=/; Secure; HttpOnly; SameSite=None</col><col class="java.lang.String" name="Server-Timing">sem_wait;dur=0, sesh_wait;dur=0</col><col class="java.lang.String" name="X-Is-Logged-In">true</col><col class="java.lang.String" name="X-Transaction-ID">4423f71587a7</col><col class="java.lang.String" name="X-Content-Type-Options">nosniff</col><col class="java.lang.String" name="Strict-Transport-Security">max-age=63072000; includeSubDomains</col></headers></HttpClient_3>

**Comment by timschaeren** [comment]
> PATCH incident/addComment Request was done against sys_id 0112576f87f375503efcec230cbb3546 Request-Body was: { "partnerId": "commvault", "incidentId": "0112576f87f375503efcec230cbb3546", "comment": "Test me Baby one more Time" } POST incident failed so don't have a ID for that, maybe the return-header extract below is helpful instead:
> 
> Server:	snow_adc
> Date:	Thu, 18 Jul 2024 11:36:58 GMT-42m 53s
> Content-Type:	application/problem+json
> Transfer-Encoding:	chunked
> Connection:	keep-alive
> Server-Timing:	sem_wait;dur=0, sesh_wait;dur=0
> Content-Encoding:	gzip
> X-Is-Logged-In:	true
> X-Transaction-ID:	9d70bed087a7
> X-Content-Type-Options:	nosniff
> Strict-Transport-Security:	max-age=63072000; includeSubDomains
> Set-Cookie:	BIGipServerpool_postchagdev=33 B, session, HttpOnly/
> Set-Cookie:	glide_user_activity=129 B, session, HttpOnly/
> Set-Cookie:	glide_node_id_for_js=65 B, session/
> Set-Cookie:	glide_session_store=33 B, session, HttpOnly/

1. PATCH /addComment
I'm showing this incident ist not associated with an interface - maybe the sys-id's got mixed up?
In this case the business rule seems to have gotten in right, when an Incident is opened via API call, the channel is set to 'monitoring' and the given 'partnerIncidentId' (which shows up in your error message as 'correlation_display') is set in the incident. The business rule checks these two facts when an API call tries to access the incident and denies the change if either is not true.

2. POST /incident
The error message indicates missing attributes in the request. Please be aware that the business rule governing mandatory fields is still work in progress. For now POST /incident should work fine with the mandatory fields specified in the [doc](https://swisspost.github.io/myit-api-doc/incidentRestAPI.html).

`{
    "partnerId" : "your_partner_id",
    "partnerIncidentId" : "1234",
    "description" : "description",
    "short_description" : "short_description",
    "causing_ci" : "sys-id or unique name of ci"
}`

**Comment by timschaeren** [comment]
> Another Variant Appeared this Weekend: PATCH https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident/addComment { "partnerId": "commvault", "incidentId": "de691cac876bce903efcec230cbb352c", "comment": "ErrorCode: [19:1328]\nFailureReason: [1] nodes failed. Failed node list: vin01a\nRecommended ..." }
> 
> Returned 500 with: {"name":"MyItRestException","message":"The action failed due to a business rule. Message: ["This Incident does not have a fieldname set.","This can not be reopened"]","status":500}
> 
> What fieldname should be missing is unclear and ticket is in status "new" so reopen comment is ambiguous.
> 
> <HttpClient_3>1721588525PENDINGfalse{"name":"MyItRestException","message":"The action failed due to a business rule. Message: ["This Incident does not have a fieldname set.","This can not be reopened"]","status":500}500Internal Server Errorsnow_adcSun, 21 Jul 2024 19:02:05 GMTapplication/problem+jsonchunkedkeep-aliveglide_session_store=0023FF1587A782146DC863540CBB35A7; Max-Age=1800; Expires=Sun, 21-Jul-2024 19:32:05 GMT; Path=/; Secure; HttpOnly; SameSite=Nonesem_wait;dur=0, sesh_wait;dur=0true4423f71587a7nosniffmax-age=63072000; includeSubDomains</HttpClient_3>

PATCH /addComment 2.0

The business rule should indeed not throw "This can not be reopened". I alerted the team developing this functionality to this bug and will keep you posted. The unhelpful message "This Incident does not have a fieldname set." is due to ongoing development trying to translate the internal fieldnames in the error message to API-caller-facing fieldnames. I will keep you posted concerning progress on this as well.

**Comment by vollraths** [comment]
> 0112576f87f375503efcec230cbb3546
Request:
https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident/addComment
{
    "partnerId": "commvault",
    "incidentId": "2f0191a587efc2146dc863540cbb3567",
    "comment": "Test me Baby one more Time"

}
Response:
{
"name": "MyItRestException",
"message": "The action failed due to a business rule. Message: [\"This Incident does not have a correlation_display set.\",\"This can not be reopened\"]",
"status": 500
}

That Issues is certainly one of mine and is not closed.
https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident?partnerId=commvault&incidentId=2f0191a587efc2146dc863540cbb3567
{
    "metadata": {
        "Caveat": "THIS IS ALPHA CODE AND SUBJECT TO CHANGE AT ANY TIM(E)!",
        "git": "IncidentRestApi-0.0.1+416-a0a1ee9-dirty",
        "build": "2024-07-22T10:03:31.753Z",
        "config": "commvault",
        "partnerId": "commvault",
        "server_system_time": "2024-07-22T14:14:09.800Z"
    },
    "data": {
        "caller_id": {
            "active": true,
            "first_name": "Technical",
            "last_name": "Commvault Dev",
            "sys_class_name": "sys_user",
            "sys_id": "8f02070a8710ce103efcec230cbb35e7",
            "user_name": "technical_commvault_dev"
        },
        "category": "incident",
        "contact_type": "monitoring",
        "impact": 4,
        "needs_attention": false,
        "number": "INC0019119",
        "opened_at": "2024-07-22T01:52:28Z",
        "opened_by": {
            "active": true,
            "first_name": "Technical",
            "last_name": "Commvault Dev",
            "sys_class_name": "sys_user",
            "sys_id": "8f02070a8710ce103efcec230cbb35e7",
            "user_name": "technical_commvault_dev"
        },
        "priority": 4,
        "state": 1,
        "sys_class_name": "incident",
        "sys_created_by": "technical_commvault_dev",
        "sys_updated_by": "technical_commvault_dev",
        "sys_updated_on": "2024-07-22T01:52:30Z",
        "u_tracker_group": {
            "active": true,
            "description": "UHD IT\nFaehigkeiten: #UHD #User Help Desk #Helpdesk #VIP-Support #Hotline #servicedesk",
            "email": "uhdit@post.ch",
            "name": "UHD-IT",
            "sys_created_by": "admin.doebeli",
            "sys_created_on": "2023-11-29T15:07:44Z",
            "sys_id": "54ef28bd87b6b190f5f463540cbb35d2",
            "sys_mod_count": 9,
            "sys_updated_by": "admin.doebeli",
            "sys_updated_on": "2024-07-03T04:56:21Z",
            "type": [
                "1st_Level"
            ],
            "u_group_phone": "+41586671414",
            "u_group_type": "assignment_group"
        },
        "incidentId": "2f0191a587efc2146dc863540cbb3567",
        "short_description": "Produktion Windows File System vqq1lf  - No data backed up in this attempt since Index validation could not complete",
        "cmdb_ci": {
            "asset_tag": "25620961",
            "department": {
                "dept_head": {
                    "sys_id": "5b95903987a08a10531785980cbb3526",
                    "sys_class_name": "sys_user"
                },
                "id": "00204926",
                "name": "IT",
                "parent": {
                    "sys_id": "fbfb973687104290531785980cbb350f",
                    "sys_class_name": "cmn_department"
                },
                "sys_created_by": "sys.ext.iam.scim_admin",
                "sys_created_on": "2024-02-15T19:48:09Z",
                "sys_id": "d41c5b3687104290531785980cbb35bd",
                "sys_mod_count": 2,
                "sys_updated_by": "sys.ext.iam.scim_admin",
                "sys_updated_on": "2024-03-02T15:01:11Z"
            },
            "environment": "Production",
            "install_status": 1,
            "life_cycle_stage": "Operational",
            "life_cycle_stage_status": "In Use",
            "manufacturer": {
                "country": "USA",
                "name": "VMware, Inc.",
                "sys_class_name": "core_company",
                "sys_id": "b1ac7c44874035106dc863540cbb35e9"
            },
            "model_id": {
                "display_name": "VMware, Inc. VMware VM IaaS",
                "life_cycle_stage": "Operational",
                "life_cycle_stage_status": "In Use",
                "manufacturer": {
                    "sys_id": "b1ac7c44874035106dc863540cbb35e9",
                    "sys_class_name": "core_company"
                },
                "name": "VMware VM IaaS",
                "sys_class_name": "cmdb_hardware_product_model",
                "sys_created_by": "import.aixboms",
                "sys_created_on": "2015-01-21T11:37:34Z",
                "sys_id": "f89400bf87f739d06dc863540cbb359d",
                "sys_updated_by": "import.aixboms",
                "sys_updated_on": "2024-07-21T23:31:32Z",
                "u_third_party": false
            },
            "name": "vqq1lf",
            "operational_status": 1,
            "short_description": "[SUSO-000741] SAP Zentralsysteme / SAP Salsa PL / Projekt / PAS-Prod / Win2022 / Java / PJG",
            "sys_class_name": "cmdb_ci_win_server",
            "sys_id": "44cf257987f54a903efcec230cbb35ec",
            "sys_updated_on": "2024-07-21T23:33:26Z"
        },
        "assignment_group": {
            "active": true,
            "description": "UHD IT\nFaehigkeiten: #UHD #User Help Desk #Helpdesk #VIP-Support #Hotline #servicedesk",
            "email": "uhdit@post.ch",
            "name": "UHD-IT",
            "sys_created_by": "admin.doebeli",
            "sys_created_on": "2023-11-29T15:07:44Z",
            "sys_id": "54ef28bd87b6b190f5f463540cbb35d2",
            "sys_mod_count": 9,
            "sys_updated_by": "admin.doebeli",
            "sys_updated_on": "2024-07-03T04:56:21Z",
            "type": [
                "1st_Level"
            ],
            "u_group_phone": "+41586671414",
            "u_group_type": "assignment_group"
        }
    }
}

**Comment by timschaeren** [comment]
> > Another Variant Appeared this Weekend: PATCH https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident/addComment { "partnerId": "commvault", "incidentId": "de691cac876bce903efcec230cbb352c", "comment": "ErrorCode: [19:1328]\nFailureReason: [1] nodes failed. Failed node list: vin01a\nRecommended ..." }
> > Returned 500 with: {"name":"MyItRestException","message":"The action failed due to a business rule. Message: ["This Incident does not have a fieldname set.","This can not be reopened"]","status":500}
> > What fieldname should be missing is unclear and ticket is in status "new" so reopen comment is ambiguous.
> > <HttpClient_3>1721588525PENDINGfalse{"name":"MyItRestException","message":"The action failed due to a business rule. Message: ["This Incident does not have a fieldname set.","This can not be reopened"]","status":500}500Internal Server Errorsnow_adcSun, 21 Jul 2024 19:02:05 GMTapplication/problem+jsonchunkedkeep-aliveglide_session_store=0023FF1587A782146DC863540CBB35A7; Max-Age=1800; Expires=Sun, 21-Jul-2024 19:32:05 GMT; Path=/; Secure; HttpOnly; SameSite=Nonesem_wait;dur=0, sesh_wait;dur=0true4423f71587a7nosniffmax-age=63072000; includeSubDomains</HttpClient_3>
> 
> PATCH /addComment 2.0
> 
> The business rule should indeed not throw "This can not be reopened". I alerted the team developing this functionality to this bug and will keep you posted. The unhelpful message "This Incident does not have a fieldname set." is due to ongoing development trying to translate the internal fieldnames in the error message to API-caller-facing fieldnames. I will keep you posted concerning progress on this as well.

This should now be fixed.
a) the fieldNames in error messages should translate correctly and have meaning to you.
b) 'this can not be reopened' no longer throws unnecessarily

Can you please check if the issue persists for you?

**Comment by vollraths** [comment]
can confirm. first tests, after re configuring the inputs to changed requirements again, look to throw better error-messages. no deeper testing or fuzzing done yet.

**Comment by timschaeren** [comment]
Thank you - closing the issue for now. Feel free to reach out, should it pop up again.
