### ISSUE TITLE
An internal error has occurred on addComment

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#3]
Get HTTP 500 when issuing addComment. 
{"message":"An internal error has occurred and has been logged with errorKey '3a4c53b187638a146dc863540cbb35c2'. Please contact the MyIT team."}

Only change to previous setup is inclusion of a partnerIncidentId that is documented as mandatory.

<url>https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident/addComment</url><method>PATCH</method><postType>Raw</postType><postContent>
{
    "partnerId": "commvault",
    "partnerIncidentId": "058f4b0e-b16c-3505-9c0b-a0b82cc6954f",
    "incidentId": "ec67577987238a146dc863540cbb35d0",
    "comment": "Test me Baby one more Time"
}
</postContent><postContentType>application/json; charset=UTF-8</postContentType>

**Comment by timschaeren** [comment]
I am able to reproduce this. While I'm investigating, you can leave out 'partnerIncidentId' from your request. While it is marked as mandatory in the doc, you don't have to use both 'incidentId' AND 'partnerIncidentId'. One of both will suffice. I'll also think about a better way to document this.

**Comment by timschaeren** [comment]
This should be fixed now - stupid coding mistake - thanks for alerting me to it.
Please let me know if it still happens for you.

**Comment by vollraths** [comment]
can confirm, works now.
