### ISSUE TITLE
Field assignement_group incorrectly populated

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#4]
Request to create Incident with a given assignment Group results in a Ticket with Dummy-Group "Anderes Team test" populated instead and no apparent option to correct that. Should the given Input-Value be invalid no Error or Warning is listed that could explain the different Value used.  

<request><url>https://myit-dev.post.ch/api/x_ssagd_inc_rest/rest/incident</url><method>POST</method><postType>Raw</postType><postContent>{
"partnerId" : "commvault",
"partnerIncidentId":"0f5fba32-ca6f-3f06-bd19-c8140f04853e",
"short_description" : "Produktion Windows File System vadonispw  - No data backed up in this attempt since Index validation could not complete",
"description":"ErrorCode: [14:275]\nFailureReason: No data backed up in this attempt since Index validation could not complete. Job will automatically restart. Please check archiveIndex.log on the MediaAgent [hsxeh02.pnet.ch] for further details\nRecommended Action: https://wikit.post.ch/display/ZDS/0:0\n\nJobDetails:\nStatus: Failed\nJobID: 2934708\nClientName: vadonispw\nAgentType: Windows File System\nInstance: DefaultInstanceName\nBackupSet: defaultBackupSet\nSubClient: default\nStartTime: Mon Jul 22 18:00:05 2024\nEndTime: \nCommCell: CommServe2 (hcszf02.pnet.ch)",
"location" : "",
**"assignment_group" : "BETR-BACKUP",**
"causing_ci" : "hcseh02",
"cmdb_ci" : "1173a87787bff9d06dc863540cbb35d5"
}
</postContent><postContentType>application/json; charset=UTF-8</postContentType>

{
	"metadata": {
		"Caveat": "THIS IS ALPHA CODE AND SUBJECT TO CHANGE AT ANY TIM(E)!",
		"git": "IncidentRestApi-0.0.1+416-a0a1ee9-dirty",
		"build": "2024-07-23T07:26:56.633Z",
		"partnerId": "commvault",
		"server_system_time": "2024-07-23T08:59:12.165Z",
		"config": "commvault"
	},
	"data": {
		"short_description": "Produktion Windows File System vadonispw  - No data backed up in this attempt since Index validation could not complete",
		**"assignment_group": {
			"sys_id": "34ed8d7d874e35903efcec230cbb359b",
			"sys_updated_by": "admin.lozano",
			"sys_created_on": "2023-10-23T10:32:00Z",
			"name": "Anderes Team test",
			"sys_mod_count": 2,
			"active": true,
			"description": "test group created by FS",
			"sys_updated_on": "2024-04-22T22:12:38Z",
			"sys_created_by": "fabian.schroeter@post.ch"
		},**
		"cmdb_ci": {
			"asset_tag": "25554481",
			"short_description": "ADONIS PROD Webserver",
			"operational_status": 1,
			"model_id": {
				"sys_id": "f89400bf87f739d06dc863540cbb359d",
				"sys_updated_by": "import.aixboms",
				"u_third_party": false,
				"life_cycle_stage_status": "In Use",
				"sys_created_on": "2015-01-21T11:37:34Z",
				"name": "VMware VM IaaS",
				"sys_updated_on": "2024-07-22T23:31:45Z",
				"display_name": "VMware, Inc. VMware VM IaaS",
				"life_cycle_stage": "Operational",
				"sys_class_name": "cmdb_hardware_product_model",
				"sys_created_by": "import.aixboms",
				"manufacturer": {
					"sys_id": "b1ac7c44874035106dc863540cbb35e9",
					"sys_class_name": "core_company"
				}
			},
			"sys_updated_on": "2024-07-22T23:34:50Z",
			"sys_class_name": "cmdb_ci_win_server",
			"manufacturer": {
				"country": "USA",
				"sys_id": "b1ac7c44874035106dc863540cbb35e9",
				"name": "VMware, Inc.",
				"sys_class_name": "core_company"
			},
			"sys_id": "1173a87787bff9d06dc863540cbb35d5",
			"environment": "Production",
			"install_status": 1,
			"life_cycle_stage_status": "In Use",
			"name": "vadonispw",
			"department": {
				"parent": {
					"sys_id": "fbfb973687104290531785980cbb350f",
					"sys_class_name": "cmn_department"
				},
				"sys_id": "d41c5b3687104290531785980cbb35bd",
				"dept_head": {
					"sys_id": "5b95903987a08a10531785980cbb3526",
					"sys_class_name": "sys_user"
				},
				"sys_updated_by": "sys.ext.iam.scim_admin",
				"sys_created_on": "2024-02-15T19:48:09Z",
				"name": "IT",
				"sys_mod_count": 2,
				"id": "00204926",
				"sys_updated_on": "2024-03-02T15:01:11Z",
				"sys_created_by": "sys.ext.iam.scim_admin"
			},
			"life_cycle_stage": "Operational"
		},
		"impact": 4,
		"causing_ci": {
			"asset_tag": "25601461",
			"short_description": "Ablösung Backup Infrastuktur - B Server 1 / Taxon 70685",
			"operational_status": 1,
			"serial_number": "WZP27210E7N",
			"model_id": {
				"sys_id": "73a408ff87f739d06dc863540cbb35f9",
				"sys_updated_by": "import.aixboms",
				"u_third_party": false,
				"life_cycle_stage_status": "In Use",
				"sys_created_on": "2023-08-23T16:41:24Z",
				"name": "UCS C240 M7",
				"sys_updated_on": "2024-07-22T23:30:54Z",
				"display_name": "Cisco UCS C240 M7",
				"life_cycle_stage": "Operational",
				"sys_class_name": "cmdb_hardware_product_model",
				"sys_created_by": "import.aixboms",
				"manufacturer": {
					"sys_id": "4eac7c44874035106dc863540cbb35f5",
					"sys_class_name": "core_company"
				}
			},
			"sys_updated_on": "2024-07-22T23:31:48Z",
			"sys_class_name": "cmdb_ci_win_server",
			"manufacturer": {
				"country": "USA",
				"sys_id": "4eac7c44874035106dc863540cbb35f5",
				"name": "Cisco Systems, Inc.",
				"sys_class_name": "core_company"
			},
			"sys_id": "7c7268f3877bb5503efcec230cbb354e",
			"environment": "Production",
			"install_status": 1,
			"life_cycle_stage_status": "In Use",
			"name": "hcseh02",
			"location": {
				"zip": "3012",
				"country": "Switzerland",
				"parent": {
					"sys_id": "e03f654f8776c6103efcec230cbb358c",
					"sys_class_name": "cmn_location"
				},
				"cmn_location_type": "room",
				"city": "Bern",
				"sys_updated_on": "2024-06-19T13:08:23Z",
				"sys_id": "0b4f6d4f8776c6103efcec230cbb3544",
				"full_name": "CH/Bern/Engehaldenstrasse 37/Engehaldenstrasse 37/1.OG/129",
				"sys_updated_by": "import.aixboms",
				"street": "Engehaldenstrasse 37",
				"sys_created_on": "2024-06-19T13:08:23Z",
				"name": "129",
				"state": "BE",
				"sys_created_by": "import.aixboms"
			},
			"department": {
				"parent": {
					"sys_id": "fbfb973687104290531785980cbb350f",
					"sys_class_name": "cmn_department"
				},
				"sys_id": "d41c5b3687104290531785980cbb35bd",
				"dept_head": {
					"sys_id": "5b95903987a08a10531785980cbb3526",
					"sys_class_name": "sys_user"
				},
				"sys_updated_by": "sys.ext.iam.scim_admin",
				"sys_created_on": "2024-02-15T19:48:09Z",
				"name": "IT",
				"sys_mod_count": 2,
				"id": "00204926",
				"sys_updated_on": "2024-03-02T15:01:11Z",
				"sys_created_by": "sys.ext.iam.scim_admin"
			},
			"life_cycle_stage": "Operational"
		},
		"description": "ErrorCode: [14:275]\nFailureReason: No data backed up in this attempt since Index validation could not complete. Job will automatically restart. Please check archiveIndex.log on the MediaAgent [hsxeh02.pnet.ch] for further details\nRecommended Action: https://wikit.post.ch/display/ZDS/0:0\n\nJobDetails:\nStatus: Failed\nJobID: 2934708\nClientName: vadonispw\nAgentType: Windows File System\nInstance: DefaultInstanceName\nBackupSet: defaultBackupSet\nSubClient: default\nStartTime: Mon Jul 22 18:00:05 2024\nEndTime: \nCommCell: CommServe2 (hcszf02.pnet.ch)",
		"sys_updated_on": "2024-07-23T08:59:11Z",
		"priority": 4,
		"sys_class_name": "incident",
		"number": "INC0019274",
		"opened_at": "2024-07-23T08:59:11Z",
		"contact_type": "monitoring",
		"sys_updated_by": "technical_commvault_dev",
		"opened_by": {
			"sys_id": "8f02070a8710ce103efcec230cbb35e7",
			"user_name": "technical_commvault_dev",
			"active": true,
			"last_name": "Commvault Dev",
			"first_name": "Technical",
			"sys_class_name": "sys_user"
		},
		"caller_id": {
			"sys_id": "8f02070a8710ce103efcec230cbb35e7",
			"user_name": "technical_commvault_dev",
			"active": true,
			"last_name": "Commvault Dev",
			"first_name": "Technical",
			"sys_class_name": "sys_user"
		},
		"state": 1,
		"category": "incident",
		"incidentId": "485cbfb5876b82143efcec230cbb3599",
		"u_tracker_group": {
			"sys_id": "34ed8d7d874e35903efcec230cbb359b",
			"sys_updated_by": "admin.lozano",
			"sys_created_on": "2023-10-23T10:32:00Z",
			"name": "Anderes Team test",
			"sys_mod_count": 2,
			"active": true,
			"description": "test group created by FS",
			"sys_updated_on": "2024-04-22T22:12:38Z",
			"sys_created_by": "fabian.schroeter@post.ch"
		},
		"partnerIncidentId": "0f5fba32-ca6f-3f06-bd19-c8140f04853e",
		"needs_attention": false,
		"sys_created_by": "technical_commvault_dev"
	},
	**"warnings": [
		"The following entries are empty and were discarded. Contact the MyIT Team for more information: location"
	],**
	"message": "Incident 485cbfb5876b82143efcec230cbb3599 created."
}

**Comment by timschaeren** [comment]
Thank you - Taking this up with the incident management stream. Will update here.

**Comment by timschaeren** [comment]
Asked for update on this from incident management development team.

**Comment by timschaeren** [comment]
assignment_group can now no longer be set by the requester. I'm in contact with you for an individual solution.
