### ISSUE TITLE
The action failed due to a business rule - channel is mandatory 

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#7]
Payload Value "channel" was made optional or removed previously, now it seems back.

CreateIncident Request failed, Error: 400{"name":"MyItRestException","message":"The action failed due to a business rule. Message: [\"channel is mandatory (Allowed Values: vendor, event).\"]","status":400} Creating ServiceNow Ticket Failed

Message states allowed values different to documentation

possible values are  'monitoring' or 'vendor'. If you are an external vendor, please choose  'vendor'. If you are an internal event-monitoring system, please choose  'monitoring'.

is it mandatory again now, will that stick? and which values are actually permitted?

**Comment by timschaeren** [comment]
Correct, 'channel' is now mandatory. The Error-message here is faulty, the documentation is correct. Thanks for making me aware - I've corrected the error message.
