### ISSUE TITLE
The callback config for this partnerId is not set properly

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#8]
All requests against ServiceNow since Friday 1800 failed with Error 500.
CreateIncident Request failed, Error: 500{"name":"MyItRestException","message":"The callback config for this partnerId is not set properly.","status":500}

**Comment by timschaeren** [comment]
Sorry, this happened because of a misconfig on our side, which has now been set right - thank you for raising the issue.
Can you please check if the issue persists for you?

**Comment by vollraths** [comment]
retried couple of attempts, worked now
