### ISSUE TITLE
DANGER OF UNNOTICED MISSING DATA

### ISSUE THREAD

**Issue by vollraths** [swisspost/myit-api-doc#9]
Get a new error when trying to retrieve CI Data, anything we can include to fix that or is backend fix required?
GetCmdbCI returned empty result:{"metadata":{"powered_by":"arc46.io","git":"squid-0.10.7+8-d9f7ce1","build":"2024-10-05T14:30:17.250Z","license_max_entities":"Unlimited","license_valid_till":"2024-12-01T23:59:59.000Z","config":"cmdb_ci_db_instance","limit_request":5,"requested_by":"technical_commvault_dev","request_received":"2024-10-05T21:42:32.655Z","parse_config":"114ms","query_start":"2024-10-05T21:42:32.769Z","query_duration":"0ms","query_returned":"2024-10-05T21:42:32.769Z","row_count":0,"requested_relations":{"cmdb_ci_db_instance":["ci_to_user_group_dynamic_inline"]},"provided_filter":"base_name=ZUKOAP01","combined_filter":"base_name=ZUKOAP01","warnings":["!!!! DANGER OF UNNOTICED MISSING DATA !!!!","The requested configuration 'cmdb_ci_db_instance' defines 'Use ServiceNow ACLs' as 'false'.","The system property 'x_ssagd_gen_read.allowAclOverride' has not been set to 'true'.","This prevents arc46 squid from disregarding ServiceNow ACLs. Please create/set system property 'x_ssagd_gen_read.allowAclOverr

**Comment by timschaeren** [comment]
This issue was fixed in the backend and should no longer occur. Please raise another issue, should it happen again.
